import { readFile, writeFile } from 'node:fs/promises';
const targets = new Set(JSON.parse(await readFile('data/target-slugs-saga-v1-quality.json', 'utf8')));
const text = await readFile('src/data/generatedHotels.ts', 'utf8');
const match = text.match(/export const generatedHotels(?:\s*:\s*any\[\])?\s*=\s*([\s\S]*);\s*$/);
const hotels = JSON.parse(match[1]).filter((hotel) => targets.has(hotel.slug));
const failures = []; const imageShortfalls = []; const retrySlugs = [];
for (const hotel of hotels) { const sections = hotel.analysis?.blogReview?.sections || []; const images = sections.filter((section) => /^https?:\/\//i.test(String(section.image?.url || section.imageUrl || ''))).length; const bodyLength = sections.reduce((n, section) => n + (section.paragraphs || []).reduce((sum, p) => sum + String(p).length, 0), 0); if (sections.length < 6) failures.push({ slug: hotel.slug, issue: `sections:${sections.length}` }); if (images < 6) imageShortfalls.push({ slug: hotel.slug, images }); if (images < 3) failures.push({ slug: hotel.slug, issue: `images:${images}` }); if (bodyLength < 700) failures.push({ slug: hotel.slug, issue: `body:${bodyLength}` }); if (!/^https?:\/\//i.test(String(hotel.imageUrl || ''))) failures.push({ slug: hotel.slug, issue: 'hero' }); if (/Fukuoka|Nagasaki|Kumamoto|福岡|長崎|熊本|후쿠오카|나가사키|구마모토/i.test(String(hotel.address || ''))) failures.push({ slug: hotel.slug, issue: 'region_outlier' }); if (hotel.qualityStatus === 'review_required' || bodyLength < 700 || sections.length < 6) retrySlugs.push(hotel.slug); }
await writeFile('data/target-hotels-saga-v1-generated.json', `${JSON.stringify(hotels, null, 2)}\n`);
await writeFile('data/target-slugs-saga-v1-retry.json', `${JSON.stringify([...new Set(retrySlugs)], null, 2)}\n`);
const summary = { count: hotels.length, withSixSections: hotels.filter((h) => (h.analysis?.blogReview?.sections || []).length >= 6).length, withSixImages: hotels.filter((h) => (h.analysis?.blogReview?.sections || []).filter((s) => /^https?:\/\//i.test(String(s.image?.url || s.imageUrl || ''))).length >= 6).length, withReferenceLinks: hotels.filter((h) => (h.referenceLinks || []).length > 0).length, retrySlugs: [...new Set(retrySlugs)], imageShortfalls, failures };
console.log(JSON.stringify(summary, null, 2)); if (failures.length) process.exitCode = 1;
